### ISSUE TITLE
Figure out a way to take scaling of systems into account in checking the kinetic energy 

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/physical-validation#8]
For large enough N, then any errors in the distribution will eventually show up (i.e. for the same algorithm, the p-value should go down as N increases).  It would be important to understand how significant this is, and if possible, find a way to make sure validity checks are relatively insensitive to the size of the system.

**Comment by ptmerz** [comment]
That's a non-issue - the Kolmogorov-Smirnov test is independent of the number of samples (see e.g. http://www.itl.nist.gov/div898/handbook/eda/section3/eda35g.htm).
